version: "3.4"
services:
    business_frontend:
      image: business_frontend
      container_name: business_frontend-dc
      ports: 
      - 3001:3000
      build:
          context: ./
          dockerfile: Dockerfile
      command: sh -c "yarn && yarn build && yarn start"    
      volumes:  
      - ./:/app
      - /app/node_modules
      env_file:
      - ./.env.local
    #   environment:
    #   - CHOKIDAR_USEPOLLING=true
    #   - NODE_ENV=development
