name: SimplePipline 

on: 
 push:
   branches: ["main"]

jobs:
  lintTest:
    name: Lint 
    runs-on: ${{ fromJSON('["ubuntu-latest", "self-hosted"]')[github.repository == 'github/docs-internal'] }} 
    steps:
     - name: Clone Repository
       uses: actions/checkout@v3
     - name: Install Dependencies
       run: | 
          echo "Installing dependencies..."
          npm install 
     - name: Run Linting  
       run: |    
         echo "Running Linting tests..."
          npm run lint
       env:
        CI: true   